- id: index
  base_relative_url: '..'
  subpages_relative_url: 'pages'
  config_dir_relative_path: '../../config'
  assets_dir_relative_path: '../assets'
  templates_dir_absolute_path: __DIR__ . '/../../public/templates'
  template_prefix_path: ''
  template_name: 'index.layin.twig.html'
- id: layouts
  base_relative_url: '../../..'
  subpages_relative_url: '../../../pages'
  config_dir_relative_path: '../../../../config'
  assets_dir_relative_path: '../../../assets'
  templates_dir_absolute_path: __DIR__ . '/../../../templates'
  template_prefix_path: 'layouts/'
  groups:
    - id: board
      template_prefix_path: 'board/'
      pages:
        - id: one_column
          template_name: 'one_column.layin.twig.html'
        - id: two_columns
          template_name: 'two_columns.layin.twig.html'
        - id: three_columns
          template_name: 'three_columns.layin.twig.html'
