html_doc_title: Layin
html_doc_description: Layin - general purpose web page layout
html_doc_keywords: layin,layout,www,web page
html_doc_author:
  name: katheroine
  email: katheroine@gmail.com
html_doc_charset: utf-8
html_doc_language: english
html_doc_language_code: en-GB
header_title: Layin
header_subtitle: General purpose layout
footer_copyright_range: 2022-2023
footer_site_name: Layin
